### ISSUE TITLE
make did not work :/

### ISSUE THREAD

**Issue by moyoteg** [klausbadelt/ffmpeg-docset#1]
wget -O build/ffmpeg-3.0.2.tar.bz2 http://ffmpeg.org/releases/ffmpeg-3.0.2.tar.bz2
build/ffmpeg-3.0.2.tar.bz2: No such file or directory
make: **\* [build/ffmpeg-3.0.2.tar.bz2] Error 1

**Comment by moyoteg** [comment]
I updated to:
FFMPEG_SOURCE_TARBALL=ffmpeg-3.1.2.tar.bz2

but without success

**Comment by klausbadelt** [comment]
The /build directory needs to exist. Should be fixed now.
