### ISSUE TITLE
ffmpeg.docset is invalid

### ISSUE THREAD

**Issue by moyoteg** [klausbadelt/ffmpeg-docset#2]
<img width="621" alt="screen shot 2016-08-11 at 11 43 06 am" src="https://cloud.githubusercontent.com/assets/574112/17598676/d366ebc0-5fb8-11e6-844e-df1ff39cca63.png">

**Comment by klausbadelt** [comment]
Running `make` probably failed before. FFmpeg changed their HTML docs. Should be fixed as of e376e3b. Please pull, `make distclean` and try again.
